version: '2'  

services: 
  server:  
    image: docvuosaari/back
    build: ./back
    expose: 
      - 8000
    ports: 
      - 8000:8000

  client: 
    image: docvuosaari/front
    build: ./front 
    ports: 
      - 5000:5000
