version: '2'  

services: 
  server:  
    image: docvuosaari/back
    build: ./back
    expose: 
      - ${APP_SERVER_PORT}
    ports: 
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}

  client: 
    image: docvuosaari/front
    build: ./front 
    ports: 
      - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}


