version: '2'  

services: 
  server:  
    image: docvuosaari/back
    build: ./back
    expose: 
      - 8000
    ports: 
      - 8000:8000
    depends_on:
      - redis
      - db
    environment:
      - REDIS = redis
      - REDIS_PORT=6379:8000

  client: 
    image: docvuosaari/front
    build: ./front 
    ports: 
      - 5000:5000

# exercise 2.5
  redis:
    container_name: redis
    image: redis
    ports: 
      - 6379:8000
    environment:
      - REDIS=redis
    #  - REDIS_PORT=6379:8000
     
# exercise 2.6
  db:
    image: postgres
    restart: unless-stopped
    environment:
      DB_USERNAME: adminer
      DB_PASSWORD: example
      POSTGRES_PASSWORD: example
      REDIS: redis
      REDIS_PORT: 6379:8000
    volumes:
      - database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database:
  files:
