version: "2"

services: 
  first_volume_exercise:  
    image: devopsdockeruh/first_volume_exercise
    build: . 
    volumes:
    - ./mydir/logs.txt:/usr/app/logs.txt
    container_name: first_volume
